# Settings for the app
app:
  # HTML Title
  title: WeHo Walk + Bike Better
  # Header name
  name: WeHo Walk + Bike Better
  # Meta description that will show up in Google search results
  meta_description: _(Share your insights and experiences to help make West Hollywood a more inviting city for pedestrians and bicyclists.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 34.089985
      lng: -118.361721
    zoom: 15
    minZoom: 14
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers:
  - id: 'labels'
    url: 'http://{s}.tiles.mapbox.com/v3/openplans.weho/{z}/{x}/{y}.png'
    type: 'tile'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  walking:
    default: walkingblue
    focused: walkingorange
    label: _(Walking)
  biking:
    default: bikinggreen
    focused: bikingorange
    label: _(Biking)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  walkingblue:
    iconUrl: /static/css/images/weho-walking-blue.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  walkinggreen:
    iconUrl: /static/css/images/weho-walking-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  walkingorange:
    iconUrl: /static/css/images/weho-walking-orange.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikingblue:
    iconUrl: /static/css/images/weho-biking-blue.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikinggreen:
    iconUrl: /static/css/images/weho-biking-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  bikingorange:
    iconUrl: /static/css/images/weho-biking-orange.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: false
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Share an idea)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    # - prompt: _(Location Title)
    #   type: text
    #   name: name
    #   attrs:
    #     - key: placeholder
    #       value: _(Location Title)
    #     - key: size
    #       value: 30
    - prompt: _(Walking or Biking?)
      name: location_type
      type: select
      options:
        - label: _(Choose...)
          value: no-choice
        - label: _(Walking)
          value: walking
        - label: _(Biking)
          value: biking
    - # prompt: _(Walk Better)
      name: walk_better
      type: select
      options:
        - label: _(Please choose...)
          value: no-choice
        - label: _(This is a comfortable place to walk.)
          value: This is a comfortable place to walk.
        - label: _(This is an uncomfortable place to walk.)
          value: This is an uncomfortable place to walk.
        - label: _(Please improve the crossing here.)
          value: Please improve the crossing here.
        - label: _(Please improve the sidewalk here.)
          value: Please improve the sidewalk here.
        - label: _(Please add pedestrian lighting here.)
          value: Please add pedestrian lighting here.
        - label: _(Please add pedestrian signage here.)
          value: Please add pedestrian signage here.
        - label: _(Please add street trees here.)
          value: Please add street trees here.
        - label: _(Other ideas (please specify).)
          value: Other ideas (please specify).
    - # prompt: _(Bike Better)
      name: bike_better
      type: select
      options:
        - label: _(Please choose...)
          value: no-choice
        - label: _(This is a comfortable place to bike.)
          value: This is a comfortable place to bike.
        - label: _(This is an uncomfortable place to bike.)
          value: This is an uncomfortable place to bike.
        - label: _(Please add a bike lane here.)
          value: Please add a bike lane here.
        - label: _(Please add bike parking here.)
          value: Please add bike parking here.
        - label: _(Please add bike signage here.)
          value: Please add bike signage here.
        - label: _(This would be a good place for bike share.)
          value: This would be a good place for bike share.
        - label: _(Other ideas (please specify).)
          value: Other ideas (please specify)
    - prompt: _(Description)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(...)
    - prompt: _( )
      inputfile_label: _(Share an image for this area)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name (optional))
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Email address (optional))
      type: text
      name: private-submitter_email_address
      attrs:
        - key: placeholder
          value: _(email@example.org)
        - key: size
          value: 30
    - prompt: _(ZIP Code (optional))
      type: text
      name: private-submitter_zipcode
      attrs:
        - key: placeholder
          value: _(ZIP Code)
        - key: size
          value: 5


survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)
