# Settings for the app
app:
  # HTML Title
  title: Our Community Map
  # Header name
  name: Our Community Map
  # Meta description that will show up in Google search results
  meta_description: Our Community Map is a mapping tool to gather crowd sourced public input our community's places, the great ones and soon-to-be great ones!


# Settings for map and layer configs
map:
  options:
    center:
      lat: 40.784896
      lng: -73.976026
    zoom: 14
    minZoom: 13
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Great Place:
    default: green_feature
    focused: green_focused
  Potential Place:
    default: yellow_feature
    focused: yellow_focused
  Problem Place:
    default: red_feature
    focused: red_focused

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  yellow_feature:
    iconUrl: /static/css/images/feature-point-yellow.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red_feature:
    iconUrl: /static/css/images/feature-point-red.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  green_feature:
    iconUrl: /static/css/images/feature-point-green.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  yellow_focused:
    iconUrl: /static/css/images/marker-focused-yellow.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red_focused:
    iconUrl: /static/css/images/marker-focused-red.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  green_focused:
    iconUrl: /static/css/images/marker-focused-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

place:
  adding_supported: true
  title: Tell us more...
  add_button_label: Add a Place
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Place Name
      type: text
      name: name
      attrs:
        - key: placeholder
          value: "Name"
        - key: size
          value: 30
    - prompt: Type of Place
      type: select
      options:
        - Great Place
        - Potential Place
        - Problem Place
      name: location_type
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
    - prompt: Description
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: Description...

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: supported
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    start_page: true

  - title: Community Places
    pages:
      - title: All
        external: true
        url: /

      - title: Great Places
        external: true
        url: /great place

      - title: Potential Places
        external: true
        url: /potential place

      - title: Problem Places
        external: true
        url: /problem place
