# Settings for the app
app:
  # HTML Title
  title: Where Should City Government Spend Our Tax Dollars?
  # Header name
  name: Where Should City Government Spend Our Tax Dollars?
  # Meta description that will show up in Google search results
  meta_description:  "Capital budget requests for the Brooklyn CB6 district"

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 40.68304631549296
      lng: -73.99699687957764
    zoom: 16
    minZoom: 15
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-uhk6289l/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  building:
    default: building
    focused: building
    label: _(Building/Facility Need)
  street:
    default: cone
    focused: cone
    label: _(Roadway/Streetscape Need)
  park:
    default: tree
    focused: tree
    label: _(Park/Open Space Need)
  building-approved:
    default: building-gold
    focused: building-gold
    label: _(Approved Building/Facility)
  street-approved:
    default: cone-gold
    focused: cone-gold
    label: _(Approved Roadway/Streetscape)
  park-approved:
    default: tree-gold
    focused: tree-gold
    label: _(Approved Park/Open Space)
  building-rejected:
    default: building-gray
    focused: building-gray
    label: _(Rejected Building/Facility)
  street-rejected:
    default: cone-gray
    focused: cone-gray
    label: _(Rejected Roadway/Streetscape)
  park-rejected:
    default: tree-gray
    focused: tree-gray
    label: _(Rejected Park/Open Space)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  tree:
    iconUrl: /static/css/images/tree.png
    shadowUrl: /static/css/images/shadow-round.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  tree-gray:
    iconUrl: /static/css/images/tree-gray.png
    shadowUrl: /static/css/images/shadow-round.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  tree-gold:
    iconUrl: /static/css/images/tree-gold.png
    iconSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  cone:
    iconUrl: /static/css/images/cone.png
    shadowUrl: /static/css/images/shadow-square.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  cone-gray:
    iconUrl: /static/css/images/cone-gray.png
    shadowUrl: /static/css/images/shadow-square.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  cone-gold:
    iconUrl: /static/css/images/cone-gold.png
    iconSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  building:
    iconUrl: /static/css/images/building.png
    shadowUrl: /static/css/images/shadow-square.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  building-gray:
    iconUrl: /static/css/images/building-gray.png
    shadowUrl: /static/css/images/shadow-square.png
    iconSize:
      width: 31
      height: 32
    shadowSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
  building-gold:
    iconUrl: /static/css/images/building-gold.png
    iconSize:
      width: 31
      height: 32
    iconAnchor:
      x: 16
      y: 25
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Identify a need
  title: Provide more information
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Add to map
  items:
    - prompt: Type of need
      type: select
      options:
        - label: _(Building/Facility Need)
          value: "Building/Facility Need"
        - label: _(Roadway/Streetscape Need)
          value: "Roadway/Streetscape Need"
        - label: _(Park/Open Space Need)
          value: "Park/Open Space Need"
      name: location_type
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Explain the need.
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: size
          value: 30
    - prompt: Your Email
      type: text
      name: private-email
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Give us a brief description of the problem or place, and the approximate time and day when you pass by here.
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: You must leave name to have your comment be visible to others.
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: Welcome
    slug: welcome
    name: welcome
    start_page: true
  - title: About
    slug: about
    name: overview