# Settings for the app
app:
  # HTML Title
  title: Safer Salem
  # Header name
  name: Safe Routes to School & Play
  # Meta description that will show up in Google search results
  meta_description:  "Safe Routes to School & Play in Salem, MA."

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 42.51954
      lng: -70.8967155
    zoom: 15
    minZoom: 11
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  TrafficIssue:
    default: puck-green
    focused: dropper-green
    label: _(Traffic issue)
  SidewalkCrosswalks:
    default: puck-blue
    focused: dropper-blue
    label: _(Sidewalk/Crosswalk issue)
  PublicSpace:
    default: puck-red
    focused: dropper-red
    label: _(Public Space needs)
  Drainage:
    default: puck-yellow
    focused: dropper-yellow
    label: _(Drainage issue)
  Lighting:
    default: puck-purple
    focused: dropper-purple
    label: _(Lighting and signal issue)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  puck-green:
    iconUrl: /static/css/images/markers/dot-70d52c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-blue:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-yellow:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-red:
    iconUrl: /static/css/images/markers/dot-e1264d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-purple:
    iconUrl: /static/css/images/markers/dot-744edc.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  dropper-green:
    iconUrl: /static/css/images/markers/marker-70d52c.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-blue:
    iconUrl: /static/css/images/markers/marker-2654d2.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-yellow:
    iconUrl: /static/css/images/markers/marker-dbcf2c.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-red:
    iconUrl: /static/css/images/markers/marker-e1264d.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-purple:
    iconUrl: /static/css/images/markers/marker-744edc.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Identify a problem
  title: Tell us more...
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Add to the map
  items:
    - prompt: ""
      type: select
      options:
        - label: _(Please choose a category)
          value: ""
        - label: _(Traffic issues)
          value: "TrafficIssue"
        - label: _(Sidewalk/Crosswalk issues)
          value: "SidewalkCrosswalks"
        - label: _(Public Space needs)
          value: "PublicSpace"
        - label: _(Drainage issues)
          value: "Drainage"
        - label: _(Lighting and signal issues)
          value: "Lighting"
      name: location_type

    # lighting checkboxes
    - prompt: Need street light
      type: checkbox
      name: lighting1
      attrs:
        - key: value
          value: Need street light
    - prompt: No walk signal or walk button
      type: checkbox
      name: lighting2
      attrs:
        - key: value
          value: No walk signal or walk button
        - key: label
          value: This is a label
    - prompt: Can’t access button
      type: checkbox
      name: lighting3
      attrs:
        - key: value
          value: Can’t access button
    - prompt: No audible signal
      type: checkbox
      name: lighting4
      attrs:
        - key: value
          value: No audible signal
    - prompt: Walk phase needs to be longer
      type: checkbox
      name: lighting5
      attrs:
        - key: value
          value: Walk phase needs to be longer
    - prompt: Walk phase needs to come sooner
      type: checkbox
      name: lighting6
      attrs:
        - key: value
          value: Walk phase needs to come sooner

    # traffic issues
    - prompt: Speeding
      type: checkbox
      name: traffic1
      attrs:
        - key: value
          value: Speeding
    - prompt: Traffic calming needed
      type: checkbox
      name: traffic2
      attrs:
        - key: value
          value: Traffic calming needed
    - prompt: Failure to yield
      type: checkbox
      name: traffic3
      attrs:
        - key: value
          value: Failure to yield
    - prompt: Dangerous intersection (please explain)
      type: checkbox
      name: traffic4
      attrs:
        - key: value
          value: Dangerous intersection (please explain)
    - prompt: Area does not feel safe or is confusing
      type: checkbox
      name: traffic5
      attrs:
        - key: value
          value: Area does not feel safe or is confusing
    - prompt: Bike infrastructure here please
      type: checkbox
      name: traffic6
      attrs:
        - key: value
          value: Bike infrastructure here please
    - prompt: Other safety issue (please specify)
      type: checkbox
      name: traffic7
      attrs:
        - key: value
          value: Other safety issue (please specify)
    
    # sidewalk issues
    - prompt: Uneven surface
      type: checkbox
      name: sidewalk1
      attrs:
        - key: value
          value: Uneven surface
    - prompt: Indirect pedestrian path
      type: checkbox
      name: sidewalk2
      attrs:
        - key: value
          value: Indirect pedestrian path
    - prompt: Unattractive
      type: checkbox
      name: sidewalk3
      attrs:
        - key: value
          value: Unattractive
    - prompt: Too narrow
      type: checkbox
      name: sidewalk4
      attrs:
        - key: value
          value: Too narrow
    - prompt: Need sidewalk
      type: checkbox
      name: sidewalk5
      attrs:
        - key: value
          value: Need sidewalk
    - prompt: Curb ramp/cut needed
      type: checkbox
      name: sidewalk6
      attrs:
        - key: value
          value: Curb ramp/cut needed
    - prompt: Too many driveways/parking lots
      type: checkbox
      name: sidewalk7
      attrs:
        - key: value
          value: Too many driveways/parking lots
    - prompt: Other sidewalk issue (please specify)
      type: checkbox
      name: sidewalk8
      attrs:
        - key: value
          value: Other sidewalk issue (please specify)

    # public space
    - prompt: More street trees please
      type: checkbox
      name: publicspace1
      attrs:
        - key: value
          value: More street trees please
    - prompt: A park here would be nice
      type: checkbox
      name: publicspace2
      attrs:
        - key: value
          value: A park here would be nice
    - prompt: A Community garden here would be nice
      type: checkbox
      name: publicspace3
      attrs:
        - key: value
          value: A Community garden here would be nice
    - prompt: Planters or other greenspace please
      type: checkbox
      name: publicspace4
      attrs:
        - key: value
          value: Planters or other greenspace please
    - prompt: Bike parking/rack here please
      type: checkbox
      name: publicspace5
      attrs:
        - key: value
          value: Bike parking/rack here please

    # drainage
    - prompt: Drain grate in bike lane
      type: checkbox
      name: drain1
      attrs:
        - key: value
          value: Drain grate in bike lane
    - prompt: Drain grate parallel to travel lane
      type: checkbox
      name: drain2
      attrs:
        - key: value
          value: Drain grate parallel to travel lane
    - prompt: Drain grate in crosswalk/sidewalk
      type: checkbox
      name: drain3
      attrs:
        - key: value
          value: Drain grate in crosswalk/sidewalk
    # other info
    - prompt: Share more details
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Give us a brief description of the problem or place.      
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: Your name (optional, will be shown on the map)
      type: text
      name: submitter_name
      attrs:
        - key: size
          value: 30
    - prompt: Your email (will be kept private)
      type: text
      name: private-email
      attrs:
        - key: size
          value: 30
    - prompt: How do you typically get around for most trips? (will be kept private)
      type: text
      name: private-mode
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: ...
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: You must leave name to have your comment be visible to others.
        - key: size
          value: 30


support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: Welcome
    slug: welcome
    name: welcome
    start_page: true
  - title: About
    slug: about
    name: overview
    start_page: false